name:                core-backend
version:             1.0.0.0
github:              "soverysour/tf-core-backend"
license:             AllRightsReserved
author:              "soverysour"
maintainer:          "sebi.f@tuta.io"
copyright:           "proprietary"

synopsis:            Core backend service for the Trade-forall platform.
category:            web

description:         Please see the README on GitHub at <https://github.com/soverysour/core-backend#readme>

ghc-options:
  - -Weverything
  - -Werror
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-foreign
  - servant-options
  # - servant-websockets -- Wait for github.com/moesenle/servant-websockets/pull/9
  - beam-core
  - beam-postgres
  - beam-migrate
  - postgresql-simple
  - hedis
  - wai
  - wai-cors
  - warp
  - fast-logger
  - aeson
  - text
  - bytestring
  - cryptonite
  - jose
  - aeson
  - string-conversions
  - resource-pool
  - time
  - time-compat
  - exceptions
  - containers
  - unordered-containers
  - vector
  - transformers
  - conduit
  - http-conduit
  - http-types
  - HTTP
  - xml-conduit
  - data-default-class
  - concurrency
  - swagger2
  - lens
  - extra
  - regex-with-pcre

library:
  source-dirs: src

executables:
  core-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - core-backend
    - htoml-megaparsec
    - unordered-containers
    - ekg
  swagger-spec-exe:
    main:                Main.hs
    source-dirs:         app-swagger
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-backend
    - servant-swagger
    - servant-auth-swagger

tests:
  core-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - core-backend
